[workspace]
resolver = "2"
members = [
#    "exchange",
    "flywheel-ast",
#    "flywheel-common",
    "flywheel-compiler",
    "flywheel-error",
#    "flywheel-interpreter",
    "flywheel-lower",
    "flywheel-parser",
    "flywheel-sources",
]

