[workspace]
resolver = "2"
members = [
    "exchange",
    "flywheel-common",
    "flywheel-compiler",
    "flywheel-interpreter",
    "flywheel-sources",
]

#[profile.release]
#debug = 1

#[dependencies.regex-automata]
#default-features = false
#features = ["std", "perf", "unicode", "syntax", ]

